    name: hetaumakeiba_v2
    description: "競馬データ管理アプリ"
    publish_to: 'none'

    version: 12.81.0+1

    environment:
        sdk: '>=3.0.0 <4.0.0'

    dependencies:
        flutter:
            sdk: flutter
        flutter_localizations:
            sdk: flutter

        # Icons
        cupertino_icons: ^1.0.8

        just_the_tooltip: ^0.0.12

        # QR Scanner
        mobile_scanner: ^7.0.1
        image_picker: ^1.1.2

        # Database
        sqflite: ^2.3.0
        path_provider: ^2.1.1
        path: ^1.8.3

        # Network & Scraping
        http: ^1.2.0
        html: ^0.15.4
        url_launcher: ^6.3.0
        charset_converter: ^2.1.1
        rss_dart: ^1.0.0

        # Chart/Graph
        fl_chart: ^0.68.0

        # Local Storage
        shared_preferences: ^2.2.3
        flutter_speed_dial: ^7.0.0
        file_picker: ^8.0.0
        share_plus: ^9.0.0
        intl: ^0.20.2
        csv: ^6.0.0
        uuid: ^4.4.0

        data_table_2: ^2.5.10

        qr_flutter: ^4.1.0
        flutter_inappwebview: ^6.0.0

        image_cropper: ^9.1.0

        flutter_slidable: ^3.1.0


    path: any
    crypto: any
    dev_dependencies:
        flutter_test:
            sdk: flutter
        flutter_lints: ^4.0.0

        flutter_launcher_icons: ^0.13.1
    flutter_launcher_icons:
        android: "launcher_icon"
        ios: true
        image_path: "assets/images/icon_app.png"
        min_sdk_android: 21

    flutter:
        uses-material-design: true
        assets:
            - assets/images/